### ISSUE TITLE
Weights available?

### ISSUE THREAD

**Issue by dscarmo** [NaveenPaluru/Segmentation-COVID-19#2]
Hello!
I would like to reproduce your model's prediction capability on different private data, do you have weights available to reproduce your training?

**Comment by NaveenPaluru** [comment]
Hi,

Thanks for your interest in our work. The trained weights are available in "Sample Testing" folder. Please refer to the Jupyter notebook "sample_test.ipynb" for implementation/testing and refer to .mat files (home folder) for data pre-processing.

Thank you
